spring:
  application:
    name: nybike
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nybikedb?serverTimezone=UTC
    username: root
    password: Wch@0817
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 80

debug: true


